### ISSUE TITLE
✖ Base repository creation failed

### ISSUE THREAD

**Issue by tapsu01** [krsbx/prisma-repo#1]
Hi, 
when i run `npx prisma-repo --base-repository`, i recieve error: `✖ Base repository creation failed`.
Can you tell me how to fix this?
![image](https://user-images.githubusercontent.com/13838358/181907987-138ea349-1f4e-49aa-965f-4f4501fd4e1c.png)

**Comment by krsbx** [comment]
did you already installed the package as a dev dep?

and can you show me your project structures as well

**Comment by tapsu01** [comment]
Yes, I installed package. I use typescript, prisma and @prisma/client ^4.1.1
Do I need to create a `src/repository` folder?
My project structure:
![image](https://user-images.githubusercontent.com/13838358/181908158-6fbfe483-5900-4c0e-a3bb-060b0f529e97.png)

**Comment by krsbx** [comment]
can you create a `repository.setting.ts` file in your project root and defines the location of generated repository? and try to create the folder that you define in the `repositoryPath` in the settings

**Comment by krsbx** [comment]
I think i just get used to have a src files a project and forgot that people can have different folder structures

let me know if it works and if you have any suggestions to make the generator better

**Comment by tapsu01** [comment]
Great!
It's worked after i created `repository.setting.ts` file. Thank for your supported

**Comment by krsbx** [comment]
cool, will working on it so it will automatically create the repository in `src/repository` and the folder if not defined in settings
thank you for letting me know about this problems

**Comment by krsbx** [comment]
for information, in versions `0.2.1` this issues has been fixed
thank you for pointing out this issues
